const router = require('express').Router();
const { queryAll, queryGet, queryRun } = require('../db');
const PDFDocument = require('pdfkit');
const { authenticate, authorize } = require('../middleware/auth');

router.get('/', authenticate, (req, res) => {
  res.json(queryAll('SELECT r.*, u.name as author FROM reports r LEFT JOIN users u ON r.generated_by = u.id ORDER BY r.id DESC'));
});

router.post('/generate', authenticate, authorize('Admin', 'HOD'), (req, res) => {
  const { title, type } = req.body;
  const faculty = queryAll('SELECT * FROM faculty');
  const students = queryAll('SELECT * FROM students');
  const docs = queryAll('SELECT * FROM documents');
  const content = JSON.stringify({ faculty, students, documents: docs, generatedAt: new Date().toISOString() });
  const result = queryRun('INSERT INTO reports (title, type, content, generated_by, status) VALUES (?, ?, ?, ?, ?)', [title || `Report - ${new Date().toLocaleDateString()}`, type || 'General', content, req.user.id, 'Published']);
  res.json({ message: 'Report generated', id: result.lastInsertRowid });
});

router.get('/:id/pdf', authenticate, (req, res) => {
  const report = queryGet('SELECT r.*, u.name as author FROM reports r LEFT JOIN users u ON r.generated_by = u.id WHERE r.id = ?', [req.params.id]);
  if (!report) return res.status(404).json({ error: 'Not found' });

  const doc = new PDFDocument({ margin: 50 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="report-${report.id}.pdf"`);
  doc.pipe(res);

  doc.fontSize(22).fillColor('#1a56db').text('AccrediTrack', { align: 'center' });
  doc.fontSize(12).fillColor('#6b7280').text('Role-Based Accreditation Data Management System', { align: 'center' });
  doc.moveDown();
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke();
  doc.moveDown();
  doc.fontSize(18).fillColor('#111827').text(report.title, { align: 'center' });
  doc.fontSize(10).fillColor('#6b7280').text(`Generated by: ${report.author} | Date: ${new Date(report.created_at).toLocaleDateString()} | Type: ${report.type}`, { align: 'center' });
  doc.moveDown(2);

  let data = {};
  try { data = JSON.parse(report.content); } catch {}

  doc.fontSize(14).fillColor('#1a56db').text('Faculty Summary');
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#1a56db').stroke();
  doc.moveDown(0.5);
  const faculty = data.faculty || [];
  doc.fontSize(10).fillColor('#111827').text(`Total Faculty: ${faculty.length}`);
  faculty.forEach(f => doc.text(`• ${f.name} | ${f.designation} | ${f.department} | Exp: ${f.experience} yrs | Publications: ${f.publications}`));
  doc.moveDown();

  doc.fontSize(14).fillColor('#1a56db').text('Student Achievements');
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#1a56db').stroke();
  doc.moveDown(0.5);
  const students = data.students || [];
  doc.fontSize(10).fillColor('#111827').text(`Total Achievements: ${students.length}`);
  students.forEach(s => doc.text(`• ${s.name} (${s.roll_number}) | ${s.achievement_type}: ${s.achievement_title} | ${s.achievement_date}`));
  doc.moveDown();

  doc.fontSize(14).fillColor('#1a56db').text('Documents');
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#1a56db').stroke();
  doc.moveDown(0.5);
  const documents = data.documents || [];
  doc.fontSize(10).fillColor('#111827').text(`Total Documents: ${documents.length}`);
  documents.forEach(d => doc.text(`• ${d.title} | Category: ${d.category} | Uploaded: ${new Date(d.created_at).toLocaleDateString()}`));

  doc.moveDown(2);
  doc.fontSize(9).fillColor('#9ca3af').text(`Generated on ${new Date().toLocaleString()} by AccrediTrack`, { align: 'center' });
  doc.end();
});

router.delete('/:id', authenticate, authorize('Admin'), (req, res) => {
  queryRun('DELETE FROM reports WHERE id = ?', [req.params.id]);
  res.json({ message: 'Report deleted' });
});

module.exports = router;
